### ISSUE TITLE
Make this work with Python 2.

### ISSUE THREAD

**Issue by ntoll** [ntoll/uflash#4]
What it says on the tin.

**Comment by funkyHat** [comment]
It's a pain that it's not possible to specify platform-specific dependencies in requirements.txt

Looks like we're missing at least mock and builtins that could easily be specified as a dependency for pip to fetch, but it would be annoying to clutter up a python3 install with them unnecessarily...

What do you think about creating a separate requirements file for python2?

**Comment by funkyHat** [comment]
https://github.com/funkyHat/uflash/tree/python2
Not quite working yet, the hex output is subtly different. The only tests that are failin are test_unhexlify and test_extract, but they are failing *because* the output from hexlify is different.

Perhaps we need more tests to ensure the *output* from hexlify is correct?

(The actual difference is an extraneous `4` on a line on its own at the end of the embedded python script (at least for our current TEST_SCRIPT :) :) ) so it wouldn't actually break anything <_< )

**Comment by funkyHat** [comment]
There's a new requirements file just for python 2, can setuptools be configured to grab dependencies from there too if it's on python 2?

**Comment by funkyHat** [comment]
I found a nice solution to this: https://caremad.io/2013/07/setup-vs-requirement/
requirements.txt can contain a line like '-e .' and it will look for dependencies inside setup.py. That allows me to check the python version there and just feels neater overall :)

**Comment by ntoll** [comment]
Nice spot! ;-)

**Comment by funkyHat** [comment]
The problem I have now is Python 2 is resisting my efforts to mock `open` ... (and still the problem where `hexlify` is generating subtly different output)

**Comment by funkyHat** [comment]
Ah. Apparently I should have put "fixes #4" instead of "fixes issue #4" in order for github to automatically close this :)

**Comment by tomviner** [comment]
This issue can be closed now?

**Comment by funkyHat** [comment]
Yep :)
